version: '3'

services:
  db:
    image: mateidanut/mtg-db-docker:db
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mtg

  backend:
    depends_on:
        - db
          #image: mateidanut/mtg-db-docker:backend
    build: ./backend-app
    ports:
      - "5000:5000"
        #tty: true
        #stdin_open: true
        #environment:
        #  - FLASK_ENV=development

  frontend:
    depends_on:
        - backend
    image: mateidanut/mtg-db-docker:frontend
    build: ./frontend-app
    ports:
      - "80:3000"
    tty: true
    stdin_open: true

  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:5.1.0
    volumes:
      - ./grafana/config.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000

volumes:
    db_init:
