version: '3'

services:
  db:
    image: mateidanut/mtg-db-docker:db
    restart: always
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mtg

  backend:
    depends_on:
        - db
    image: mateidanut/mtg-db-docker:backend
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  frontend:
    depends_on:
        - backend
    image: mateidanut/mtg-db-docker:frontend
    ports:
      - "8080:80"

volumes:
    db_init:
